<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-06-14 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2019-06-29 12:47:26
 */
?>
<?php
$helper = $block->getAjaxHelper();
$btnTextColor = $helper->getBtnTextColor();
$btnContinueBackground = $helper->getBtnContinueBackground();
$btnContinueHover = $helper->getBtnContinueHover();
$btnViewcartBackground = $helper->getBtnViewcartBackground();
$btnViewcartHover = $helper->getBtnViewcartHover();
$countDown = ($helper->getCountDownTime() > 0) ? $helper->getCountDownTime() : 0;
?>
<style>
    #magepow_ajaxcart_popup .btn-continue .continue {
        background: #<?php echo $block->escapeHtml($btnContinueBackground); ?>;
        color: #<?php echo $block->escapeHtml($btnTextColor); ?>;
    }

    #magepow_ajaxcart_popup .btn-continue .continue:hover {
        background: #<?php echo $block->escapeHtml($btnContinueHover); ?>;
    }

    #magepow_ajaxcart_popup .btn-viewcart .viewcart {
        background: #<?php echo $block->escapeHtml($btnViewcartBackground); ?>;
        color: #<?php echo $block->escapeHtml($btnTextColor); ?>;
    }

    #magepow_ajaxcart_popup .btn-viewcart .viewcart:hover {
        background: #<?php echo $block->escapeHtml($btnViewcartHover); ?>;
    }
</style>

<script type="text/javascript">
    require(['jquery', 'magepowAjaxcart', 'domReady!'], function($, magepowAjaxcart){
            $('body').on('contentUpdated', function () {
                if($.magiccart) $('body').magiccart({
                    "addUrl": "<?php echo $block->escapeUrl($block->getUrl('ajaxcart')); ?>",
                    "quickViewUrl": "<?php echo $block->escapeUrl($block->getUrl('ajaxcart/product/view/')); ?>",
                    "addToCartSelector": "<?php echo $block->escapeJsQuote($helper->getAddToCartSelector()); ?>",
                    "countDown": "<?php echo $countDown; ?>"
                });
            });
    });
</script>
