<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-07-15 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2019-07-23 21:18:27
 */
  $helper = $this->helper('Magepow\Ajaxcart\Helper\Data');
  $heightScroll = $helper->getHeightScroll();
  $currentProduct = $block->getCurrentProduct();
  $id = $currentProduct->getId();
  $_productStock = $block->getStockItem($id);
  $timer = $helper->getTimer($currentProduct);
  $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
                    ->init($currentProduct, 'product_base_image')
                    ->constrainOnly(TRUE)
                    ->keepAspectRatio(TRUE)
                    ->keepTransparency(TRUE)
                    ->keepFrame(FALSE)
                    ->resize(80, 80)->getUrl();
?>
<?php if($_productStock->getIsInStock()): ?>
  <div class="stickyCart">
    <div class="stickyChild">
    <div class="contentHide">
    <div class="clSticky" id="timerSticky">
      <?php if($timer): ?>
      <?php echo $timer; ?>
      <?php else: ?>
      <div class="stickyProductName"><?php echo $block->escapeHtml(__($currentProduct->getName())) ?></div>
      <?php endif; ?>
      </div>
    </div>
    <div class="contentHide">
    <div class="clSticky"><div class="imgBorder"><div class="stickyImg" style="background-image: url(<?php echo $imageUrl ?>);"></div></div></div></div>
    <div class="contentHide">
    <div class="clSticky" id="parentQtySticky">
      <?php if ($currentProduct->getTypeId() == 'grouped'): ?>
      <div class="field qty">
        <div class="product-qty">
        <div class="control custom-qty">
          <input type="number"
               name="qty"
               id="qtyGrouped"
               maxlength="12"
               value="1"
               title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
               />
           <div class="btn-plus">
              <button  type="button" class="increase items" onclick="var result = document.getElementById('qtyGrouped'); var qtyGrouped = result.value; if( !isNaN( qtyGrouped )) result.value++;return false;">
            <i class="fa fa-angle-up"></i>
          </button> 
           <button  type="button" class="reduced items" onclick="var result = document.getElementById('qtyGrouped'); var qtyGrouped = result.value; if( !isNaN( qtyGrouped ) && qtyGrouped > 1 ) result.value--;return false;">
              <i class="fa fa-angle-down"></i>
          </button>  
          </div>  
        </div>
      </div>
        </div>
      <?php else: ?>
        <div class="field qty">
        <div class="product-qty">
        <div class="control custom-qty">
          <input type="number"
               name="qty"
               id="qtySticky"
               maxlength="12"
               value="1"
               title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
               />
           <div class="btn-plus">
                     <button  type="button" class="increase items" onclick="var result = document.getElementById('qtySticky'); var qtySticky = result.value; if( !isNaN( qtySticky )) result.value++;return false;">
            <i class="fa fa-angle-up"></i>
          </button> 
           <button  type="button" class="reduced items" onclick="var result = document.getElementById('qtySticky'); var qtySticky = result.value; if( !isNaN( qtySticky ) && qtySticky > 1 ) result.value--;return false;">
              <i class="fa fa-angle-down"></i>
          </button>  
          </div>  
        </div>
      </div>
        </div>
        <?php endif; ?>
      </div>
    </div>
    <?php if ($currentProduct->getTypeId() == 'bundle'): ?>
    <div class="contentHide contentShow"><div class="clSticky"><button class="btn-cart-bottom btnCustom">Customize</button></div></div>
      <?php else: ?>
    <div class="contentHide contentShow"><div class="clSticky"><button id="btnSticky" class="btn-cart-bottom">Add To Cart</button>
    </div></div>
  <?php endif; ?>
  </div>
  </div>
<?php endif; ?>
<?php
$formData = [
    'stickyCart'    				    =>  '.stickyCart',
    'qtySticky'						      =>	'#qtySticky',
    'btnCustom'                 =>  '#btnCustom',
    'quantity'                  =>  '.quantity',
    'qtyGrouped'                =>  '#qtyGrouped',
    'btnSticky'                 =>  '#btnSticky'
];
$stickyData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "magepowStickycart": {
            "jsonData":<?php /* @noEscape */ echo $stickyData; ?>,
            "ScrollHeight": <?php   echo $heightScroll; ?>
            }
        }
    }
</script>

