<?php
/*
 * @category: Magepow
 * @copyright: Copyright (c) 2014 Magepow (http://www.magepow.com/)
 * @licence: http://www.magepow.com/license-agreement
 * @author: MichaelHa
 * @create date: 2019-06-14 17:19:50
 * @LastEditors: MichaelHa
 * @LastEditTime: 2019-06-29 12:46:38
 */
?>
<?php
$helper = $block->getAjaxHelper();
$addUrl = $block->getUrl('ajaxcart');
$quickViewUrl = $helper->isModuleEnabled('Magiccart_Alothemes') ? $block->getUrl('alothemes/product/view/') : $block->getUrl('ajaxcart/index/view/');
?>
<script type="text/x-magento-init">
    {
        "#ajax-suggest": {
        "magepowAjaxcart": {
        "addUrl": "<?php echo $block->escapeUrl($addUrl); ?>",
        "isSuggestPopup": true,
        "quickViewUrl": "<?php echo $block->escapeUrl($quickViewUrl); ?>",
        "addToCartSelector": "<?php echo $block->escapeHtml($helper->getAddToCartSelector()); ?>"
    }
}
}
</script>